### ISSUE TITLE
작업물 생성 안됨

### ISSUE THREAD

**Issue by AZDR5** [redstar-javscraper/redstar_upscaler#10]
![화면 캡처 2024-08-13 235432](https://github.com/user-attachments/assets/f47eacce-58f5-4894-bb74-45ababc17553)

작업 실행하면 일단 작업 폴더에 프레임단위로 이미지 파일들이 생성&업스케일 되는 부분 까진 확인되는데
이후 작업(Flowframes 등)으로 이어지지 않고 그대로 작업 완료 상태가 되는데 작업수행 폴더로 설정한 경로에 결과물이 남질 않습니다.

Flowframes 사용 체크 해제한 조건으로도 시도 해봤지만 결과는 같네요. 원인을 모르겠습니다

**Comment by ghost** [comment]
이 경우, 앞단계에서 오류가 나서 그럴 수 있습니다
실행전 명령어 창에 있는 명령들을 수동으로 실행해 보시고, 문제가 되는 단계를 확인해보세요. 
또, 이미지를 보니 해상도(후) 크기가 큰데 flowframe 설정에 최대 사이즈 제한도 있으니 설정도 보세요
