### ISSUE TITLE
이상한 오류가뜹니다

### ISSUE THREAD

**Issue by ohmygodto2** [redstar-javscraper/redstar_upscaler#11]
![화면 캡처 2024-11-15 165943](https://github.com/user-attachments/assets/2a1ea440-37f7-435a-8a5b-a6dab7c82131)
이런 오류가 뜨고 실행이안됩니다

**Comment by ghost** [comment]
Flowframe 설치가 안되있을 경우 발생할 수 있는 오류입니다. 
코드상 해당 부분은 오류처리가 되지 않은 상태에서 flowframe 정보를 가져올 수 없어서 발생한 문제이므로 flowframe 설치하시면 실행은 되실겁니다. 조만간 오류처리 후 업데이트 할게요

**Comment by ohmygodto2** [comment]
감사합니다
