### ISSUE TITLE
Flowframes 오류

### ISSUE THREAD

**Issue by horizon24z** [redstar-javscraper/redstar_upscaler#12]
ffmpeg과 realesrgan은 잘 작동하나 flowframes 사용시 아래 오류가 뜹니다.
![스크린샷 2024-12-18 015954](https://github.com/user-attachments/assets/5fb2da50-d1f5-49dc-8414-bba7b107e860)

**Comment by redstar-javscraper** [comment]
> ffmpeg과 realesrgan은 잘 작동하나 flowframes 사용시 아래 오류가 뜹니다. ![스크린샷 2024-12-18 015954](https://private-user-images.githubusercontent.com/192019797/396593161-5fb2da50-d1f5-49dc-8414-bba7b107e860.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0ODA1OTksIm5iZiI6MTczNDQ4MDI5OSwicGF0aCI6Ii8xOTIwMTk3OTcvMzk2NTkzMTYxLTVmYjJkYTUwLWQxZjUtNDlkYy04NDE0LWJiYTdiMTA3ZTg2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOFQwMDA0NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZThiMTdkNjFjNTM0ZTI5YmVkNDFlOWIyN2ZlZDkwZjYzOWMwMmU1MThmZTcxOTZlYWM0MjRjZTZlNjg5YmE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ldCLIPcmguASCWX9ijnAtcLHcZJoUDxG_cMLWs9v00U)

flowframes 버전 및 프로그램에서 flowframes 설정은 어떤 상태로 하셨는지요?

**Comment by ghost** [comment]
flowframes 버전 및 프로그램에서 flowframes 설정은 어떤 상태로 하셨는지요?

**Comment by horizon24z** [comment]
1.36.0 버전입니다.
![image](https://github.com/user-attachments/assets/e144b118-87ec-4f87-94af-566b8cc9d31c)

flowframes를 제가 선택한 경로에 설치했을 때 오류가 떴는데
flowframes: C:\Users\ [본인 계정] \AppData\Local\Flowframes 경로에 재설치를 하니 오류가 해결되었습니다. 감사합니다.

**Comment by ghost** [comment]
증상 알려주셔서 감사합니다. 비슷한 상황에서 코드 검토해보겠습니다

**Comment by ghost** [comment]
코드 검토 결과 flowframes 경로 변경 시 AI모델 콤보박스에 중복 입력이 되는 바람에 중복 추가된 항목으로 보간작업이 실행됨으로 인해 생긴 오류로 확인되었으며, 0.1.92 버전으로 업로드 하겠습니다.

**Comment by horizon24z** [comment]
항상 감사합니다.
