### ISSUE TITLE
보안관련 이슈

### ISSUE THREAD

**Issue by ghost** [redstar-javscraper/redstar_upscaler#2]
바이러스토탈 = 미검출(안전)
윈도우디펜더 = 트로이젠 sabsik.te.a!ml 검출 (심각)
찝찝해서 일단 제거했음

**Comment by ghost** [comment]
디펜더가 설치된 환경에서 빌드한건데 이상하네요
확인해볼께요

**Comment by ghost** [comment]
> 바이러스토탈 = 미검출(안전) 윈도우디펜더 = 트로이젠 sabsik.te.a!ml 검출 (심각) 찝찝해서 일단 제거했음

래딧 검색결과 파이썬 컴파일된 일부 파일에서 나타난다고 하네요. 디펜더 버전, 검출내용을 보내주시면 ms 윈도우 디펜더팀에 보내서 검출예외 티켓 띄울게요

**Comment by ghost** [comment]
![1](https://github.com/redstar-javscraper/redstar_upscaler/assets/141465716/0c57aa59-7b73-4056-ae6f-dc18f66b125e)
![2](https://github.com/redstar-javscraper/redstar_upscaler/assets/141465716/f104b415-4233-4019-8c29-2c10d17cc4da)

혹시 디펜더 업데이트를 안해서 오진떴나 했는데 업데이트 후에는 다른 위협으로 바뀜. sabsik이면 긴가민가해서 불안했는데  wacatac은 윈도우 디펜더 오진일 확률이 매우 높은 검출내역중에 하나라고 알고있음 ㅋㅋ:: 아오 윈도우디펜더시치

**Comment by ghost** [comment]
디펜더 팀으로 부터 예외처리 확인 받았습니다.
향후 버전업 파일마다 오탐처리 요청은 어려울 수 있으니 참고 바랍니다.


Submission details Refresh
redstar upscaler v0.1.1.exe
Submission ID: c2e9731f-8d7b-4bbe-bbcf-0af68a0c321e

Status: Completed

Submitted by: 

Submitted: Aug 5, 2023 오후 4:21:31

User Opinion: Incorrect detection

Analyst comments:


At this time, the submitted files do not meet our criteria for malware or potentially unwanted applications. The detection has been removed. Please follow the steps below to clear cached detections and obtain the latest malware definitions.

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"

Alternatively, the latest definition is available for download here: https://docs.microsoft.com/microsoft-365/security/defender-endpoint/manage-updates-baselines-microsoft-defender-antivirus

Thank you for contacting Microsoft.

Click here for more information

**Comment by jokk6703** [comment]
좋은 프로그램 만들어주셔서 감사합니다!

아마 디펜더가 오진했던 거는 이 프로그램이 Pyinstaller로 빌드되어서 그런 거 같아요.. Pyinstaller로 만들어지는 바이러스가 꽤 많고 내장한 pyc 파일을 제외하면 구조 자체는 대부분 비슷비슷하기 때문에 클라우드 전송으로 MS 서버에 넘어갔다가 자동으로 오진된 거 같아요!

Pyinstaller 쪽에서도 관련한 Issue가 있었어요! https://github.com/pyinstaller/pyinstaller/issues/5854

인터넷에 찾아보니까 이런 방법도 있던데 개발자님 혹시 다음 업뎃 때에는 시도해주시면 감사하겠습니다!
https://angelplayer.tistory.com/354

**Comment by ghost** [comment]
> 좋은 프로그램 만들어주셔서 감사합니다!
> 
> 아마 디펜더가 오진했던 거는 이 프로그램이 Pyinstaller로 빌드되어서 그런 거 같아요.. Pyinstaller로 만들어지는 바이러스가 꽤 많고 내장한 pyc 파일을 제외하면 구조 자체는 대부분 비슷비슷하기 때문에 클라우드 전송으로 MS 서버에 넘어갔다가 자동으로 오진된 거 같아요!
> 
> Pyinstaller 쪽에서도 관련한 Issue가 있었어요! [pyinstaller/pyinstaller#5854](https://github.com/pyinstaller/pyinstaller/issues/5854)
> 
> 인터넷에 찾아보니까 이런 방법도 있던데 개발자님 혹시 다음 업뎃 때에는 시도해주시면 감사하겠습니다! https://angelplayer.tistory.com/354

좋은 내용 감사합니다! 다음 버전에서 적용 가능한지 검토해 볼게요
