### ISSUE TITLE
창 크기 조절이 가능할까요?

### ISSUE THREAD

**Issue by Arise8548** [redstar-javscraper/redstar_upscaler#3]
https://ac-p1.namu.la/20230818sac/bcd8f3e393e67bc1d328e1b78f514e48d23ae6d62cacb2796f055c7bae3232e0.png?dummy=&expires=1692348589&key=Q5Ev5uReBggyiR00ekHEFQ&type=orig

안녕하세요 해상도를 uhd에 200%배율로 사용중이라 그런지 화면이 저렇게 나오네요 100%으로 돌리면 정상적으로 보이긴하지만 폰트등 전체적으로 작아져서 불편해져서요.. 혹시 자체적으로 크기조절을 할수 있는지 궁금합니다

**Comment by ghost** [comment]
이미지는 안 보이네요.
창 크기는 고려해 보겠습니다

- UI별 폰트 크기는 수정했습니다. 다음 버전에 적용될 예정입니다

**Comment by redstar-javscraper** [comment]
UI별 폰트 크기는 수정했습니다. 다음 버전에 적용될 예정입니다

**Comment by redstar-javscraper** [comment]
UI별 폰트 크기는 수정했습니다. 다음 버전에 적용될 예정입니다
