### ISSUE TITLE
1.5버전 사용이후 업스케일링 화면이 깨지던데 원본은 멀쩡한데 왜그런걸까요??

### ISSUE THREAD

**Issue by MANGS11z** [redstar-javscraper/redstar_upscaler#4]
1.5버전 사용이후 업스케일링 화면이 깨지던데 원본은 멀쩡한데 왜그런걸까요??

![00000001](https://github.com/redstar-javscraper/redstar_upscaler/assets/142608405/ec365d08-2694-441d-a619-b90d51bcd09a)

모든 사진이 저런형태로 저장되던데 무슨 이유가 있을까요?

**Comment by ghost** [comment]
원본 영상을 보내주시면 확인해볼게요
