### ISSUE TITLE
키고 동영상을 넣고 설정후 시작하면 바로 오류가 생기면서 꺼집니다.

### ISSUE THREAD

**Issue by baekhj1217** [redstar-javscraper/redstar_upscaler#5]
https://github.com/redstar-javscraper/redstar_upscaler/assets/143097955/00b82cbe-1c8b-4174-aa33-5df6e3a812a4

봐 주시고 어떤게 문제인지 지적 부탁드립니다.

**Comment by ghost** [comment]
작업 영상으로는 확인이 어려울것 같습니다. 작업에 사용한 동영상 원본 파일을 보내주시면 확인해 볼게요

**Comment by baekhj1217** [comment]
영상 문제일 줄 알고 저도 영상을 바꿔봤는데 한 5개 정도 똑같은 결과로 나와서 영상 문제는 아닌거 같아서 질문 드려요

**Comment by baekhj1217** [comment]
> 작업 영상으로는 확인이 어려울것 같습니다. 작업에 사용한 동영상 원본 파일을 보내주시면 확인해 볼게요


https://github.com/redstar-javscraper/redstar_upscaler/assets/143097955/2ed79bb1-c0bd-43d0-8db8-e6ba25803a17
일단은 이것입니다

**Comment by ghost** [comment]
[https://drive.google.com/file/d/1nr8U5spM-2O7VLEnhEelsswFWnh4SdBg/view?usp=drive_link](url)
위 링크에서 받은 파일로 실행하고 화면에 표시되는 디버깅 메시지를 보내주세요

**Comment by ghost** [comment]
[https://drive.google.com/file/d/1nr8U5spM-2O7VLEnhEelsswFWnh4SdBg/view?usp=drive_link](url)
위 링크에서 받은 파일로 실행하고 화면에 표시되는 디버깅 메시지를 보내주세요

**Comment by baekhj1217** [comment]
> [https://drive.google.com/file/d/1nr8U5spM-2O7VLEnhEelsswFWnh4SdBg/view?usp=drive_link](url) 위 링크에서 받은 파일로 실행하고 화면에 표시되는 디버깅 메시지를 보내주세요

이 파일로 실행하니 업스케일이 진행되는거 같습니다 혹시 무슨 차이가 있는건가요? 디버깅 메시지는 이러합니다.
Thread 시작
Main Thread 시작
for working start
temp_path: C:\Users\pro\Downloads\realesrgan-ncnn-vulkan-20220424-windows\45kbt4uYD9temp_realesrgan_path: C:\Users\pro\Downloads\realesrgan-ncnn-vulkan-20220424-windows\45kbt4uYD9\realesrgan
작업 시작, 작업번호: 1
작업명령: C:\Users\pro\Downloads\ffmpeg-6.0-full_build\ffmpeg-6.0-full_build\bin\ffmpeg.exe -i C:\Users\pro\Downloads\realesrgan-ncnn-vulkan-20220424-windows\onepiece_demo.mp4 -r 23.98 -q:v 1 -qmin 1 -qmax 1 C:\Users\pro\Downloads\realesrgan-ncnn-vulkan-20220424-windows\45kbt4uYD9\%08d.jpg
리턴코드: 0
작업 종료: 1
작업 시작, 작업번호: 2
작업명령: C:\Users\pro\Downloads\realesrgan-ncnn-vulkan-20220424-windows\realesrgan-ncnn-vulkan.exe -i C:\Users\pro\Downloads\realesrgan-ncnn-vulkan-20220424-windows\45kbt4uYD9 -o C:\Users\pro\Downloads\realesrgan-ncnn-vulkan-20220424-windows\45kbt4uYD9\realesrgan -n realesr-animevideov3-x2 -s 2 -j 1:2:2 -f jpg
리턴코드: 0
작업 종료: 2
작업 시작, 작업번호: 3
작업명령: C:\Users\pro\Downloads\ffmpeg-6.0-full_build\ffmpeg-6.0-full_build\bin\ffmpeg.exe -hwaccel cuda -f image2 -r 23.98 -i C:\Users\pro\Downloads\realesrgan-ncnn-vulkan-20220424-windows\45kbt4uYD9\realesrgan\%08d.jpg -vcodec libx265 -crf 20 -pix_fmt yuv420p C:\Users\pro\Downloads\realesrgan-ncnn-vulkan-20220424-windows\45kbt4uYD9\mergedvideo.mp4
리턴코드: 0
작업 종료: 3
작업 시작, 작업번호: 4
작업명령: C:\Users\pro\Downloads\ffmpeg-6.0-full_build\ffmpeg-6.0-full_build\bin\ffmpeg.exe -i C:\Users\pro\Downloads\realesrgan-ncnn-vulkan-20220424-windows\onepiece_demo.mp4 -f mp3 -ab 192000 -vn -async 1 C:\Users\pro\Downloads\realesrgan-ncnn-vulkan-20220424-windows\45kbt4uYD9\extractaudio.mp3
리턴코드: 0
작업 종료: 4
작업 시작, 작업번호: 5
작업명령: C:\Users\pro\Downloads\ffmpeg-6.0-full_build\ffmpeg-6.0-full_build\bin\ffmpeg.exe -i C:\Users\pro\Downloads\realesrgan-ncnn-vulkan-20220424-windows\45kbt4uYD9\mergedvideo.mp4 -i C:\Users\pro\Downloads\realesrgan-ncnn-vulkan-20220424-windows\45kbt4uYD9\extractaudio.mp3 -c copy C:\Users\pro\Downloads\realesrgan-ncnn-vulkan-20220424-windows\[REDSTAR]onepiece_demo.mp4
리턴코드: 0
작업 종료: 5
작업 시작, 작업번호: 6
작업명령: C:\Users\pro\AppData\Local\Flowframes\Flowframes.exe C:\Users\pro\Downloads\realesrgan-ncnn-vulkan-20220424-windows\[REDSTAR]onepiece_demo.mp4 -factor=0 -start -quit-when-done -ai=0 -output-mode=0 -model=7
리턴코드: 0
작업 종료: 6
작업폴더 및 데이터 삭제
작업 완료6

이게 맞다면 말이죠

**Comment by ghost** [comment]
try~catch만 제거했을 뿐인데 잘 되는군요. 다음 버전에 적용해서 배포할게요
