### ISSUE TITLE
애매한 해상도의 영상을 업스케일링 하고 싶습니다.

### ISSUE THREAD

**Issue by DaeHyeon-Kim** [redstar-javscraper/redstar_upscaler#6]
애매한 해상도의 영상을 해상도 변경해서 활용하고 싶습니다.
720x480, 1280x720 등 영상의 해상도가 각자 달라 업스케일링 하는데 애매한 경우가 있어서 요청 드립니다.

ffmpeg 명령어 중에 특정 해상도로 프레임 뽑는 옵션이 있는데 이걸 사용해서 540p
ex) ffmpeg -i 원본영상.mp4 -qscale:v 1 -qmin 1 -qmax 1 -vsync 0 -s 960(비율에 따라 변경)x540 input1\%08d.jpg 
로 뽑아서 2배수 1080p 4배수 2160p로 뽑는 처리가 들어갔으면 좋겠습니다.

**Comment by ghost** [comment]
다음 버전에 고려해 보겠습니다

**Comment by ghost** [comment]
0.1.6 버전에 적용했습니다

**Comment by DaeHyeon-Kim** [comment]
의견 반영해 주셔서 감사합니다
