### ISSUE TITLE
사용관련 문의

### ISSUE THREAD

**Issue by chanming1920** [redstar-javscraper/redstar_upscaler#7]
우선 개발자님 좋은 프로그램에 감사합니다. 현재 노트북으로 작업 진행하고 있는데 사양이 높지 않다보니 시간이 꽤 오래걸리고 있습니다. 질문 몇가지만 드리려고 하는데 강제중지 버튼을 누를 시 작업 삭제가 되는건가요? 아니면 일시정지처럼 작업을 잠시 멈춰둘 수 있는건지 궁금합니다. 눌러보면 되는 문제지만 혹시나 현재까지 진행률이 날아갈까 하는 마음에 올리는 점 죄송합니다. 또한 정지시킨 후에 장치를 재부팅해도 이어서 작업을 진행할 수 있는지 궁금해 문의드립니다. 귀한 시간 혹시나 여유가 되시면 답변 부탁드립니다.

**Comment by ghost** [comment]
프로그램 구성상 외부 cmd를 통해 실행하기 때문에 정지는 되지 않습니다, 강제중지는 현재 진행중인 작업이 완료되면 다음 작업을 하지 않겠다는 것이므로 바로 중단되지는 않습니다. 그리고 재부팅시 재작업을 하는 기능은 아직 없습니다
