### ISSUE TITLE
0.1.6 과 0.1.7 의 실행조건이 다른가요?

### ISSUE THREAD

**Issue by Kyaruster** [redstar-javscraper/redstar_upscaler#8]
안녕하세요.

구글링을 통하여 들어왔으며, 좋은 프로그램을 제공하여 주셔서 감사합니다.

다름이 아니라 현재 올려주신 릴리즈의 0.1.7을 받아 실행하였으나, 아래와 같이 오류 메세지를 나타내었습니다.

![스크린샷 2024-03-03 162725](https://github.com/redstar-javscraper/redstar_upscaler/assets/162006533/6e016e83-dc50-43df-8845-4c231708c4c6)
＊테스트 환경 ( Windows 10 22H2, Windows 11 23H2 )

테스트 환경에서 동일하게 나왔으며, 0.1.7 제공 파일 중 Main.ui 파일이 있어 이에 그 파일을 해당 스크린샷에 나온 파일 명으로 바꾸어 재시도를 하였습니다.

그리고 결과는 아래와 같습니다.
![스크린샷 2024-03-03 162758](https://github.com/redstar-javscraper/redstar_upscaler/assets/162006533/9662935c-1368-4b21-b07e-3c2345c670bd)
＊테스트 환경 ( Windows 10 22H2, Windows 11 23H2 )

0.1.6은 위의 테스트 환경에서 문제 없이 실행되어 별도로 문제는 없었으나, 0.1.7을 올려주신 만큼 사용을 해보고 싶었지만 혹시 제가 놓친 별도의 문제가 있는지  하여 질문 드리고자 이슈 남겨드립니다. 

감사합니다.

**Comment by ghost** [comment]
사용해 주셔서 감사합니다.
두 버전간의 차이점은 빌드방식과 오류 수정 부분이 있는데 일부 환경에서 실행파일 경로를 못찾아서 설정 저장이 안되는 문제로 기존 단일파일을 다중파일로 빌드했습니다. 개발pc에서만 테스트 되서 제기하신 문제점은 다음주 중으로 살펴볼게요

**Comment by Kyaruster** [comment]
시간 내서 답변을 주셔서 감사합니다! 좋은 결과를 기대합니다

**Comment by ghost** [comment]
해당 오류는 릴리즈 시 ui파일을 빼먹었기 때문에 발생한 문제로, 변경 후 빌드하였습니다.

**Comment by Kyaruster** [comment]
> 해당 오류는 릴리즈 시 ui파일을 빼먹었기 때문에 발생한 문제로, 변경 후 빌드하였습니다.

감사합니다. 언제나 행복한 하루 되십시요!
